target("unit_tests")
    set_kind("binary")
    set_default(true)
    add_deps("board", "bus", "scale_core", "scale_proto", "nau7802", "lis2dw12", "tmp102")
    add_packages("doctest")
    add_files("*.cpp")
    add_includedirs(".")
    add_defines("SCALE_TEST_FIXTURE_DIR=\"" .. path.join(os.scriptdir(), "fixtures") .. "\"")
