target("replay")
    set_kind("binary")
    set_default(true)
    add_deps("scale_core")
    add_files("replay.cpp")
    add_includedirs(".")

target("flowbench")
    set_kind("binary")
    set_default(true)
    add_deps("scale_core")
    add_files("flowbench.cpp")
    add_includedirs(".")
